language: android

sudo: required

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

before_install:
   - ulimit -t 514029
   - chmod +x gradlew
   - sudo apt-get update -qq
   - sudo apt-get install -y libxml2-dev
   - mem=($(free -m | head -2 | tail -1)); if [ ${mem[6]} -eq 0 ]; then export BAD_VM=1; fi

install:
   - ./gradlew --version # show version and download Gradle Wrapper when is not present in cache
   - ./gradlew clean # clean project and download Android dependencies when are not present in cache
   - ./gradlew assemble --stacktrace

# Emulator Management: Create, Start and Wait
before_script:
   - ./execute wait-for-device-ready inexistent
   - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
   - emulator -avd test -no-skin -no-audio -no-window &
   - curl http://is.gd/android_wait_for_emulator > android-wait-for-emulator
   - chmod u+x android-wait-for-emulator
   - ./android-wait-for-emulator
   - adb shell input keyevent 82 &

script:
  - ./gradlew connectedCheck

android:
  components:
    # The BuildTools version used by your project
    - build-tools-22.0.1
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    # The SDK version used to compile your project
    - android-22
    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-22
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-22

notifications:
  email:
    recipients:
      - ranjeet@applozic.com


