language: android

sudo: false

before_install:
   - ulimit -t 514029
   - chmod +x gradlew
   #- sudo apt-get update -qq
   #- sudo apt-get install -y libxml2-dev
   - mem=($(free -m | head -2 | tail -1)); if [ ${mem[6]} -eq 0 ]; then export BAD_VM=1; fi

script: ./gradlew test

android:
  components:
    # The BuildTools version used by your project
    - build-tools-22.0.1
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    # The SDK version used to compile your project
    - android-22
    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-22
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-22

notifications:
  email:
    recipients:
      - global@mobitexter.net
      - devashish@applozic.com
      - adarsh@applozic.com
      - ranjeet@applozic.com
      - sunil.kumar@mobitexter.net
      
after_success: ./scripts/travis_upload_release_to_github.py      

